# Utiliser une image de base Node.js
FROM node:18

# Définir le répertoire de travail
WORKDIR /

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances du projet
RUN npm install

# Copier les fichiers du projet dans le conteneur
COPY . .

# Exposer le port 3000
EXPOSE 4173

# Commande pour démarrer l'application
CMD ["npm", "run", "preview"]